### ISSUE TITLE
How about Galileo

### ISSUE THREAD

**Issue by utack** [mvglasow/satstat#109]
Hi,  
I wanted to know how (potential) Galileo Satellites are displayed.  
Thanks

**Comment by mvglasow** [comment]
See the [wiki](https://github.com/mvglasow/satstat/wiki/NMEA-IDs#galileo) for satellite systems.

First of all, it depends on the device. SatStat will display whatever the device reports.

As for Galileo, I am not aware of any NMEA IDs being assigned so far (which is what SatStat uses to determine which system a particular satellite belongs to). That means, if you were to take the present version of SatStat and install it on a future device with Galileo support, then get a fix from Galileo, the following would probably happen:

- Position data would take Galileo into account, possibly merged with whatever GPS, GLONASS and Beidou report. That depends on the chip inside the device.
- The sky plot would show the Galileo satellites just like any other satellites.
- The SNR bar chart would display the Galileo satellites either as unknown or not at all – that depends on the NMEA IDs that will ultimately get assigned to them.

If anybody has information on the NMEA IDs for Galileo, feel free to open an issue for that, and I'll add that range.

**Comment by utack** [comment]
Thanks!

**Comment by barbeau** [comment]
Just opened https://github.com/mvglasow/satstat/issues/110 with Galileo ID info.
