### ISSUE TITLE
Offline Map of Germany incomplete

### ISSUE THREAD

**Issue by jw243** [mvglasow/satstat#112]
The offline map of Germany is totally incomplete at the moment. There are absolutely no roads, buildings, etc included. It just shows the coastline and a few names, nothing else. The download is surprisingly small with just 20MB. It used to work and the download used to be much larger (>500MB as far as I remember).

Could you replace the download file with a working version again?

Thanks.

**Comment by mvglasow** [comment]
Thanks for spotting this one! I don’t build or host these map files—SatStat relies on map files offered by the mapsforge team (allowing for maps to be shared with other apps, such as Radiobeacon).

Something seems to have gone wrong there—I’ve opened a bug there at https://github.com/mapsforge/mapsforge/issues/917. It’s being taken care of and should be fixed soon.

If you can’t wait and you still have a working copy of the Germany map somewhere, you can manually copy it into the map directory on your device. SatStat doesn’t care how the file got there—it’ll use any valid map file it finds in its map directory, and whether a map file needs to be updated is determined just by looking at the timestamp.

You could also try to get the Germany map from http://openmaps.eu/mapsforgedownload?country=Germany&purpose=any&format=mapsforge&sw=any&device=any&opsys=any&search=any&landcontour=any&dem=any&pack=any#android (scroll up to get the download for Germany). Not sure how well these maps will work with SatStat—in any case, be sure to delete the file (or move it away) before you download a working map of Germany again!

I’ll close this one as I can’t do anything about it.
