### ISSUE TITLE
Closes on change from sat display to others

### ISSUE THREAD

**Issue by ithink314** [mvglasow/satstat#116]
On Nexus 6 with Android 7.1.1 build N6F26Q.

**Comment by mvglasow** [comment]
Can you pull a logcat right after the crash and post it here? That would help me narrow down the issue.

**Comment by ithink314** [comment]
Strange. After installing alogcat, this app is working again. There were several app updates earlier today, including Android system webview too, so maybe that helped. Sorry for the false alarm.

**Comment by gadgetguy08** [comment]
I am having the same issue and have a log cat.

Note that it does not crash when airplane mode is on and just wifi is active.
Also phone is cdma



06-10 11:54:43.516 I/ActivityManager(630): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.vonglasow.michael.satstat/.ui.MainActivity bnds=[184,574][360,831] (has extras)} from uid 10031 on display 0
06-10 11:54:43.624 V/NlpLocationProvider(1586): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10084 com.vonglasow.michael.satstat}
06-10 11:54:46.344 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-54-46.log
06-10 11:54:46.354 E/AndroidRuntime(3357): Process: com.vonglasow.michael.satstat, PID: 3357
06-10 11:54:46.354 E/AndroidRuntime(3357): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
06-10 11:54:46.354 E/AndroidRuntime(3357): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
06-10 11:54:46.354 E/AndroidRuntime(3357): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
06-10 11:54:46.354 E/AndroidRuntime(3357): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
06-10 11:54:46.357 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:54:46.478 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-54-46.log
06-10 11:54:46.863 W/ActivityManager(630): Activity pause timeout for ActivityRecord{4211474 u0 com.vonglasow.michael.satstat/.ui.MainActivity t1096 f}
06-10 11:54:47.370 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{bb63888 u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{2d9c80d 3357 com.vonglasow.michael.satstat/10084/u0 remote:e6c82a4}: process crashing
06-10 11:54:47.852 I/ActivityManager(630): Killing 3357:com.vonglasow.michael.satstat/u0a84 (adj 900): crash
06-10 11:54:47.871 I/ActivityManager(630): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.vonglasow.michael.satstat/.ui.MainActivity (has extras)} from uid 10031 on display 0
06-10 11:54:47.923 I/ActivityManager(630): Start proc 3600:com.vonglasow.michael.satstat/u0a84 for activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:54:48.082 W/System  (3600): ClassLoader referenced unknown path: /data/app/com.vonglasow.michael.satstat-1/lib/arm
06-10 11:54:48.203 V/NlpLocationProvider(1586): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10084 com.vonglasow.michael.satstat}
06-10 11:54:50.104 E/AndroidRuntime(3600): Process: com.vonglasow.michael.satstat, PID: 3600
06-10 11:54:50.104 E/AndroidRuntime(3600): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
06-10 11:54:50.104 E/AndroidRuntime(3600): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
06-10 11:54:50.104 E/AndroidRuntime(3600): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
06-10 11:54:50.104 E/AndroidRuntime(3600): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
06-10 11:54:50.111 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:54:50.132 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-54-50.log
06-10 11:54:50.204 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{27c1beb u-1 android.net.wifi.RSSI_CHANGED} to ReceiverList{a966585 3600 com.vonglasow.michael.satstat/10084/u0 remote:c1bcafc}: process crashing
06-10 11:54:50.622 W/ActivityManager(630): Activity pause timeout for ActivityRecord{ac60007 u0 com.vonglasow.michael.satstat/.ui.MainActivity t1096 f}
06-10 11:54:51.759 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{a4e1d63 u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{a966585 3600 com.vonglasow.michael.satstat/10084/u0 remote:c1bcafc}: process crashing
06-10 11:54:52.536 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:54:52.550 I/ActivityManager(630): Killing 3600:com.vonglasow.michael.satstat/u0a84 (adj 900): crash
06-10 11:56:53.517 I/ActivityManager(630): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.vonglasow.michael.satstat/.ui.MainActivity bnds=[184,574][360,831] (has extras)} from uid 10031 on display 0
06-10 11:56:53.576 I/ActivityManager(630): Start proc 3992:com.vonglasow.michael.satstat/u0a84 for activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:56:53.664 W/System  (3992): ClassLoader referenced unknown path: /data/app/com.vonglasow.michael.satstat-1/lib/arm
06-10 11:56:53.782 V/NlpLocationProvider(1586): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10084 com.vonglasow.michael.satstat}
06-10 11:56:54.286 I/ActivityManager(630): Displayed com.vonglasow.michael.satstat/.ui.MainActivity: +721ms
06-10 11:56:56.172 E/AndroidRuntime(3992): Process: com.vonglasow.michael.satstat, PID: 3992
06-10 11:56:56.172 E/AndroidRuntime(3992): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
06-10 11:56:56.172 E/AndroidRuntime(3992): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
06-10 11:56:56.172 E/AndroidRuntime(3992): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
06-10 11:56:56.172 E/AndroidRuntime(3992): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
06-10 11:56:56.174 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:56:56.240 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-56-56.log
06-10 11:56:56.684 W/ActivityManager(630): Activity pause timeout for ActivityRecord{89f65a5 u0 com.vonglasow.michael.satstat/.ui.MainActivity t1100 f}
06-10 11:56:57.506 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{deae05c u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{e05931b 3992 com.vonglasow.michael.satstat/10084/u0 remote:b37792a}: process crashing
06-10 11:56:58.324 I/ActivityManager(630): Killing 3992:com.vonglasow.michael.satstat/u0a84 (adj 900): crash
06-10 11:56:58.348 I/ActivityManager(630): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.vonglasow.michael.satstat/.ui.MainActivity (has extras)} from uid 10031 on display 0
06-10 11:56:58.410 I/ActivityManager(630): Start proc 4050:com.vonglasow.michael.satstat/u0a84 for activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:56:58.513 W/System  (4050): ClassLoader referenced unknown path: /data/app/com.vonglasow.michael.satstat-1/lib/arm
06-10 11:56:58.622 V/NlpLocationProvider(1586): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10084 com.vonglasow.michael.satstat}
06-10 11:56:59.177 I/ActivityManager(630): Displayed com.vonglasow.michael.satstat/.ui.MainActivity: +796ms
06-10 11:57:00.581 E/AndroidRuntime(4050): Process: com.vonglasow.michael.satstat, PID: 4050
06-10 11:57:00.581 E/AndroidRuntime(4050): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
06-10 11:57:00.581 E/AndroidRuntime(4050): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
06-10 11:57:00.581 E/AndroidRuntime(4050): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
06-10 11:57:00.581 E/AndroidRuntime(4050): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
06-10 11:57:00.584 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:57:00.597 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-57-00.log
06-10 11:57:01.092 W/ActivityManager(630): Activity pause timeout for ActivityRecord{7c458eb u0 com.vonglasow.michael.satstat/.ui.MainActivity t1100 f}
06-10 11:57:02.235 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{f44bcc6 u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{2003889 4050 com.vonglasow.michael.satstat/10084/u0 remote:374b790}: process crashing
06-10 11:57:02.492 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:57:02.515 I/ActivityManager(630): Killing 4050:com.vonglasow.michael.satstat/u0a84 (adj 900): crash
06-10 11:57:03.832 I/ActivityManager(630): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.vonglasow.michael.satstat/.ui.MainActivity bnds=[184,574][360,831] (has extras)} from uid 10031 on display 0
06-10 11:57:03.878 I/ActivityManager(630): Start proc 4113:com.vonglasow.michael.satstat/u0a84 for activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:57:04.040 W/System  (4113): ClassLoader referenced unknown path: /data/app/com.vonglasow.michael.satstat-1/lib/arm
06-10 11:57:04.162 V/NlpLocationProvider(1586): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10084 com.vonglasow.michael.satstat}
06-10 11:57:04.653 I/ActivityManager(630): Displayed com.vonglasow.michael.satstat/.ui.MainActivity: +795ms
06-10 11:57:05.752 E/AndroidRuntime(4113): Process: com.vonglasow.michael.satstat, PID: 4113
06-10 11:57:05.752 E/AndroidRuntime(4113): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
06-10 11:57:05.752 E/AndroidRuntime(4113): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
06-10 11:57:05.752 E/AndroidRuntime(4113): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
06-10 11:57:05.752 E/AndroidRuntime(4113): 	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
06-10 11:57:05.754 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:57:05.776 D/MediaScannerReceiver(3319): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.vonglasow.michael.satstat/files/satstat-2017-06-10-15-57-05.log
06-10 11:57:06.275 W/ActivityManager(630): Activity pause timeout for ActivityRecord{b3744d9 u0 com.vonglasow.michael.satstat/.ui.MainActivity t1101 f}
06-10 11:57:06.363 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{396386b u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{b55246f 4113 com.vonglasow.michael.satstat/10084/u0 remote:3b7eb4e}: process crashing
06-10 11:57:06.708 W/BroadcastQueue(630): Skipping deliver [background] BroadcastRecord{95c599d u-1 android.net.wifi.RSSI_CHANGED} to ReceiverList{b55246f 4113 com.vonglasow.michael.satstat/10084/u0 remote:3b7eb4e}: process crashing
06-10 11:57:07.594 W/ActivityManager(630):   Force finishing activity com.vonglasow.michael.satstat/.ui.MainActivity
06-10 11:57:07.613 I/ActivityManager(630): Killing 4113:com.vonglasow.michael.satstat/u0a84 (adj 900): crash

**Comment by mvglasow** [comment]
Thanks for the logcat. This seems really strange indeed—very similar to #104, including the same stack trace, but the exception is a different one (which doesn’t quite make sense to me—the system looks for an external library, but SatStat doesn’t use any).

Since I’ve already fixed #104, I’ll push an update to F-Droid in the next days. I’d appreciate your feedback if that fixes it!

**Comment by gadgetguy08** [comment]
I compiled 3.2 and it has fixed it.  I tested on 2 CDMA devices.

Thanks for fixing this. It is a very useful app!

**Comment by ithink314** [comment]
The CDMA connection and my seeing the problem one time but not later can make sense, and not be related to updates as I before suspected. I use Project Fi, and was traveling when the problem occurred. I may have been on a CDMA network one time and on GSM or WiFi later. I will try the update when it hits F-droid. Thanks for the app and fix! 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ithink314** [comment]
The CDMA connection and my seeing the problem one time but not later can make sense, and not be related to updates as I before suspected. I use Project Fi, and was traveling when the problem occurred. I may have been on a CDMA network one time and on GSM or WiFi later. I will try the update when it hits F-droid. Thanks for the app and fix! 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mvglasow** [comment]
@gadgetguy08 thanks for testing and reporting back! I’ve just tagged a new version and it should appear on F-Droid in the next few days.

**Comment by mvglasow** [comment]
The new version hit the F-Droid repo a couple of days ago, closing this issue.
