### ISSUE TITLE
Wrong height

### ISSUE THREAD

**Issue by preheater** [mvglasow/satstat#131]
Hi,
at the moment i am on the seychelles at mahe in the "bord mer hotel". I am a view meters from the beach but satstat shows the height -44 meters.
I think it's wrong.
Maybe you can check and fix it.
Kind regards
Peter

**Comment by kadarivan** [comment]
It's just 5 meters error:
http://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html

**Comment by preheater** [comment]
Hi,
i am not so familiar with gps data but -44 meter high is under sea level. 
Other apps show 9 m above sea level.
Maybe it is a point of view for the calculation.

Kind regards
Peter


Am 3. Oktober 2017 23:59:04 schrieb kadarivan <notifications@github.com>:

**Comment by sm4rk0** [comment]
What @kadarivan is saying is that GPS doesn't report the true altitude above the sea level. Check [this article](http://www.esri.com/news/arcuser/0703/geoid1of3.html) for detailed explanation.

On the other hand, @mvglasow it would be nice to have the correction automatically computed, like in [OsmAnd](http://download.osmand.net/). Does this sound like a valid Feature Request?

**Comment by gdt** [comment]
I would say that the point of satstat is to show what the device is reporting, in as raw a way as possible.   GPS calculates ellipsoidal height, but generally on the GPS side of the GPS/computer boundary there is a geoid height applied to get some sort of pseudo-orthometric height (altitude, more or less).

So I don't think satstat should get into doing that, but if something is supposed to be ellipsoidal height, maybe that should be measured.

I wonder though, if generally altitude is reported, and the OPs phone is different.

**Comment by mvglasow** [comment]
SatStat was created mainly as a debugging tool. So if the GPS is reporting bogus data (such as you being in a boat while your GPS claims you’re beneath the water surface) and SatStat shows this, it’s doing its job.

As per the Android API docs (see https://developer.android.com/reference/android/location/Location.html#getAltitude() for details), altitude is (or should be) relative to the WGS84 reference ellipsoid.

If someone would like to take a stab at implementing some kind of correction, I encourage you to go ahead.

**Comment by gdt** [comment]
Being in a boat (on the ocean) and seeing a GPS height report that is negative is not necessarily wrong.  The Android spec says that getAltitude is "Get the altitude if available, in meters above the WGS 84 reference ellipsoid. "    The reference ellipsoid and the geoid (what people call MSL) are not the same thing.

**Comment by gdt** [comment]
See also #144.
