### ISSUE TITLE
crashes with openbmap location provider with nearly-1GB us.sqlite

### ISSUE THREAD

**Issue by gdt** [mvglasow/satstat#139]
This is a fuzzy report, but I am curious if someone else is seeing this.

I'm running satstat from 2017-06-19 on a relatively modern no-gapps ROM.   I have unifiednlp and several providers.  Until recently, satstat had behaved very well.
Just now I added DejaVu, and have been watching the map view with satstat.  All has seemed sensible.  I updated the mapsforge file from June of 2016 to recent today, and drove for about 45 minutes with that new file and DejaVu with no issues.  Then, I updated the radiocells/openbmap database to the currently-available us.sqlite, which is nearly 1 GB, compared to under 200 MB from before (yes, somethhng seems amiss)., and disabled DejaVu and enabled the openbmap backend.   I was seeing mostly-reasonable data, but found that satstat would crash every few minutes.

So I wonder if something is going wrong with such a huge database, and if the location backend or satstat is running out of memory, or something else.  No logs at the moment, but I can try to get one.

(I've also inquired about the unexpected size of the radiocells db file.)

**Comment by mvglasow** [comment]
Yes please, do send me a log. When SatStat crashes, it should normally write a crash log to its data dir (`Android/data/com.vonglasow.michael.satstat/files`), the filename contains the timestamp.

Any location data from SatStat is obtained via the location API, i.e. SatStat doesn’t even know there is a database involved. The only way an openbmap database could crash SatStat would be if the DB causes the location provider to send unexpected data—the log might help me find out.

On a side note, I use SatStat with the openbmap location provider. I process my own DB (from my latest logs plus anything that has been updated on the server side), which is currently at 1.57 GB, and I am not seeing any crashes.

**Comment by gdt** [comment]
So far, no log.  I am wondering if my phone (old, not that much RAM) was running out of memory, perhaps partially due to the openbmap provider, plus OsmAnd.   Today there were no issues.

**Comment by mvglasow** [comment]
If SatStat doesn’t write a log file, you can simply pull a logcat the next time it crashes.

**Comment by gdt** [comment]
No further crashes have happened since the ones reported above (and a reboot).   So I am now fairly sure that my phone was having more general trouble.   I'll followup with real data if I ever have it, which I'm guessing I won't, so I'll close to reduce clutter.   Sorry for the noise....
