### ISSUE TITLE
No Glonass-detection and no AGPS-data update on one device but on another identical one

### ISSUE THREAD

**Issue by noc-jfcbs** [mvglasow/satstat#155]
I'm absolutely not convinced if I'm reporting a bug but at least I want to mention this weird situation.

Running Satstat v3.3 on two identical devices (details below), and while the two devices are "sitting" side by side one of the devices doesn't detect Glonass and doesn't update the AGPS-data due to an ostensibly not available network (but the network is definitely available and used by other applications) while the second device recognises Glonass and performs the AGPS-data update.

Screenshots from both devices are attached, also a Logcat from the device with the issue. For privacy reasons, some parts of the screenshots are pixeled out, some private data in the Logcat are "X"-ed out.
Hopefully, someone can assist in troubleshooting.

Devices: Samsung GT-i9305
Configuration (identical for both devices):
Satstat v3.3
OS Ressurection Remix-Nougat v5.8.5-final, Magisk v16.0, Boeffla-Kernel, XPosed, XPrivacyLua, AFWall+
All permissions grated to Satstat. ROM- and kernel settings absolutely the same. Same settings in XPrivacyLua and AFWall+.
[Device1_Matlog_2018-06-10-13-26-40.txt](https://github.com/mvglasow/satstat/files/2090196/Device1_Matlog_2018-06-10-13-26-40.txt)
![device1_screenshot_20180610-133429](https://user-images.githubusercontent.com/21972717/41235471-65bb1936-6d7e-11e8-9ae1-255be9688bc9.png)
![device1_screenshot_20180610-133450](https://user-images.githubusercontent.com/21972717/41235473-68915bc0-6d7e-11e8-9128-579f32a5e879.png)
![device1_screenshot_20180610-133509](https://user-images.githubusercontent.com/21972717/41235485-6f2263d0-6d7e-11e8-96c1-a0643d887575.png)
![device1_screenshot_20180610-133529](https://user-images.githubusercontent.com/21972717/41235497-7323f66a-6d7e-11e8-88e4-149a90770f4d.png)
![device1_screenshot_20180610-133545](https://user-images.githubusercontent.com/21972717/41235503-76b5cb78-6d7e-11e8-857c-d12b533e5514.png)
![device2_screenshot_20180610-133438](https://user-images.githubusercontent.com/21972717/41235510-7c8d0aac-6d7e-11e8-8ff0-7123accd4907.png)
![device2_screenshot_20180610-133502](https://user-images.githubusercontent.com/21972717/41235514-7f6627ea-6d7e-11e8-9793-40f177cc61ff.png)
![device2_screenshot_20180610-133520](https://user-images.githubusercontent.com/21972717/41235521-83cd8bd4-6d7e-11e8-9590-9bee8a107461.png)
![device2_screenshot_20180610-133539](https://user-images.githubusercontent.com/21972717/41235530-87940e82-6d7e-11e8-91ce-2c611c8950b1.png)
![device2_screenshot_20180610-133555](https://user-images.githubusercontent.com/21972717/41235542-8a868778-6d7e-11e8-9c13-11daf3c4f9a9.png)

**Comment by mvglasow** [comment]
As for AGPS: SatStat checks if it has a connection to the Internet before attempting to refresh AGPS. The procedure is taken from AOSP source code.

In the above example the check appears to have failed, thus SatStat aborts the attempt. The second device appears to have a working Internet connection.

As one devices seems to have mobile data turned off and the other does not seem to have a working SIM at all, both would need to rely on wifi for their Internet connection.

Is this behavior reproducible? If not, it might have been an intermittent connectivity issue which Android did not pick up but SatStat did.

Also, I see that the your phone seems to report weird values for the mobile network: for Vodafone.de I would expect to see 232/02 for the MCC/MNC, not 001/01.

**Comment by mvglasow** [comment]
Another thing I see is that the toast notification on one device shows the app icon while on the other it doesn’t. That is a hint that the device configurations may not be 100% identical.

**Comment by noc-jfcbs** [comment]
Michael, very obvious, SatStat is **not** buggy; the issue definitely rests with my device. In my personal opinion, SatStat is the very best application of its kind, and that not only because its FLOSS. Under these considerations, it's even more noticable that you had a look into my issue, offered up some of your valuable time and are trying to support me.
And I apologise that I forgot to mention both devices are GApps-free and utilising microG with great satisfaction. I hope this doesn't matter. Usually, I use SatStat to confirm that GPS is working after I flashed a ROM or an upgrade; i.e. I really used SatStat on the "faulty" device the last time in September, and then I clearly remember it also discovered GLONASS and updated AGPS. Since then, SatStat was simply resting retired on the phone.
I made some additional trials yesterday evening and this morning but before I report some wierd experiences again, please allow me to answer your questions.
> Also, I see that the your phone seems to report weird values for the mobile network: for Vodafone.de I would expect to see 232/02 for the MCC/MNC, not 001/01.

This is due to the use of XPosedLua that fakes the MCC/MNC; however, it should be irrelevant as the required features "location", "sensors" and "read network data" were not enabled i.e. SatStat received unfaked location values, both GPS and network. This morning, I completely disabled XPosedLua for SatStat but it's "behaviour" hasn't changed.
> Another thing I see is that the toast notification on one device shows the app icon while on the other it doesn’t. That is a hint that the device configurations may not be 100% identical.

Oh, configuration of both devices is really the same except that the one without a SIM is my backup device and therefore currently carries a smaller application portfolio. However, I realised that the ROM's Privacy Guard was enable on the "faulty" device for SatStat; I disabled it this morning but the results remained unchanged as to be expected.
Regarding the network: My personal best pratice is to disable mobile data when connected to a WiFi-network. In that case, both devices are connected to our home network (fiber with 100 Mbit/s up & down); even in the garden where I also test GPS we've great Wifi reception due to an AVM powerline.
And I've to admit, I've not noticed the app icon you mentioned. Actually, I've never seen it before - and didn't know that SatStat might display one in the notification bar. And during yesterday evening's and this morning's use of SatStat this app icon wasn't displayed. I simply don't know what it is.

And affirmative, the issue is reproducible. First three screenshots are of yesterday evening. Again, only GPS detection but not Glonass. And AGPS update failed again with the same notification.
But I also recognised two additional things: Please observe the elevation shown by SatStat, and the elevations provided by my map/navigation app and another GPS app: While the latter two one are correct (about 44 m), SatStat is off by nearly 100%. Despite very small differences, position is recognised very precisely by all three of them (location mode was at sensors only).

During this mornings trial, location mode was "high" and network connection to our home network available (just added a screenshot of my browser to prove). Interestingly, SatStat now also showed one SBAS satellite (but yet no Glonass) and as to be expected, no AGPS update. Maybe interesting that SatStat indicates True North about 90° off; however, the correct True North indication was provide by a different GPS app (refer to second last screenshot).

And finally, by the last screenshot taken while out for shopping I'd simply like to provide evidence that AGPS data update is also impossible while on mobile data (all other app utilising mobile data are working). In this screenshot, position is again correct but elevation and true north indication are wrong.

Please advise if you want me to conduct further testing.
![screenshot_20180620-210201](https://user-images.githubusercontent.com/21972717/41728719-ff1beb7e-7566-11e8-97a8-238d9528f435.png)
![screenshot_20180620-210220](https://user-images.githubusercontent.com/21972717/41728720-ff39dbe8-7566-11e8-93a2-fd19e8908469.png)
![screenshot_20180620-210338](https://user-images.githubusercontent.com/21972717/41728721-ff546440-7566-11e8-9c7b-04aaf37fc8cd.png)
![screenshot_20180621-091620](https://user-images.githubusercontent.com/21972717/41728722-ff75bfb4-7566-11e8-90bc-f3f9e46fdf47.png)
![screenshot_20180621-091703](https://user-images.githubusercontent.com/21972717/41728723-ff928388-7566-11e8-8758-28043b1415fe.png)
![screenshot_20180621-091732](https://user-images.githubusercontent.com/21972717/41728724-ffad2562-7566-11e8-94ec-6b099d5bf8d4.png)
![screenshot_20180621-091856](https://user-images.githubusercontent.com/21972717/41728725-ffc74e06-7566-11e8-8c75-66ef7e89ec55.png)
![screenshot_20180621-100926](https://user-images.githubusercontent.com/21972717/41728726-00256b58-7567-11e8-8173-becaabb77bd8.png)

**Comment by noc-jfcbs** [comment]
Update:
I guess I forgot to mention that both devices are GApps-free and running with microG.
Just as a trial, on the "problem device" I clean flashed my ROM but this time with OpenGApps pico, today. Installed FDroid followed by Satstat.
In this configuration, Satstat positively initiates an update of the AGPS data. However, still no Glonass detection but I don't want to rule out a respective hardware/sensor issue on the device.
Reverted to the Nandroid backup, and again no AGPS data update.

Conclusion: As to be expected, Satstat works as advertised. The culprit rests somewhere within my system/configuration. Going to further explore. If I find the reason I'll update this ticket.

Closing this ticket as the issue isn't obviously Satstat related.

**Comment by noc-jfcbs** [comment]
The issue with no AGPS updates finally solved.
I had unfrozen the ROM inherent browser and CaptivePortalLogin. Afterwards, Satstat initiated the update of the AGPS data.
ROM inherent browser and CaptivePortalLogin back into frozen status; Satstat still initiating the AGPS update.
