### ISSUE TITLE
Main (satellite) screen stops working

### ISSUE THREAD

**Issue by teohhanhui** [mvglasow/satstat#156]
My location can be determined in the map screen, but the main (satellite) screen is only able to show the number of satellites (0/n).

It worked the first time I used the app, but for some reason it has stopped working. I've tried force stopping, clearing app data and revoking and re-allowing location access. But the problem is still not fixed. How do I provide useful information for debugging?

**Comment by teohhanhui** [comment]
Reinstalled the app but that didn't help either. Perhaps I'll have to try rebooting the device (lol).

**Comment by mvglasow** [comment]
What is the color of the marker you’re seeing in the map screen?

If you get a blue marker but no red marker, your device does not have a GPS fix (and hence little information from GPS) but is obtaining a location from the Network location provider, based on nearby wifi networks. In that case it is normal to see very little information on the satellite screen—the number of satellites used and possibly some satellites in the sky plot and SNR view, but not much more.

GPS reception varies heavily between devices (although more recent devices seem to be doing better): some will pick up a GPS signal only when outside and without any nearby obstructions, while others will pick up a GPS signal even when indoors and a few meters away from the nearest window. Under less-than-perfect conditions, the device may simply take more time to pick up a usable GPS signal.

**Comment by teohhanhui** [comment]
Unfortunately there's nothing at all. It worked earlier (on the same day before it stopped working). 

[screenshot_20180619-102011](https://user-images.githubusercontent.com/548843/41585447-620fb418-73aa-11e8-8743-92ab6efdfd96.png)

**Comment by teohhanhui** [comment]
You're right. It's just because my device couldn't get a satellite fix. Perhaps some kind of UI hint would be useful to let the user know that it's still trying to acquire a fix.
