### ISSUE TITLE
Why the `PasvLocListenerService` service is always running ?

### ISSUE THREAD

**Issue by Massedil** [mvglasow/satstat#163]
I have activated the options to be notified when another app is using the GPS.

On my phone the `PasvLocListenerService` service is always running after SatStat is launched and never stopped.

If I kill the app (so the service is not running), when another app is using the GPS, the notification icon is well displayed, I think thanks to this :

```
<receiver android:name="GpsEventReceiver" >
	<intent-filter>
		<action android:name="android.location.GPS_ENABLED_CHANGE" />
		<action android:name="android.location.GPS_FIX_CHANGE" />
		<action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
		<action android:name="android.net.wifi.STATE_CHANGE" />
		<action android:name="com.vonglasow.michael.satstat.AGPS_DATA_EXPIRED" />
	</intent-filter>
</receiver>
```

So I wonder why there is a service kept running.

Is it normal ?

Thanks for this very useful app ! :)

**Comment by mvglasow** [comment]
This is in order to display a notification whenever an app uses the GPS, and also to trigger periodic updates of AGPS data. Both can be disabled in Settings. This should not create any noticeable extra load, so I don’t consider it an issue.
