### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by DaleBCooper** [mvglasow/satstat#164]
@mvglasow 
Just in case you are not aware someone published your app on Google Play:
[Location, Sensor & Radio Network Status](https://play.google.com/store/apps/details?id=com.drunkdeveloper.location.sensor.radio.network.wifi.status)

**Comment by mvglasow** [comment]
Thanks for the heads up. While I am in principle OK with people redistributing my app, this particular case violates the GPL in two places: For one, changing the package name and app title constitutes  modification, for which the developer would need to publish the source code. The app description includes a link to this repository, but not to the modifications. Secondly, the description states that by using the app, the user is bound by terms of usage which, among others, prohibit commercial use or copying. I wrote to the developer’s support address, asking that these two things be fixed.

**Comment by mvglasow** [comment]
I got a response from the developer today, he fixed both issues.
