### ISSUE TITLE
DMS computation incorrect

### ISSUE THREAD

**Issue by jimktrains** [mvglasow/satstat#165]
![screenshot_20181123-004231](https://user-images.githubusercontent.com/40850/48929860-6031bc00-eeba-11e8-9d95-a7fb35cf9de9.png)
![screenshot_20181123-004855](https://user-images.githubusercontent.com/40850/48929861-6031bc00-eeba-11e8-96de-487c6bcabb15.png)

The seconds in the longitude is wrong because the longitude is negative.

PR coming.

**Comment by mvglasow** [comment]
Merged. Thanks for hunting this down and fixing it!
