### ISSUE TITLE
Support MGRS/UTMREF

### ISSUE THREAD

**Issue by maugsburger** [mvglasow/satstat#41]
I'd really love being able to get my location also in http://en.m.wikipedia.org/wiki/Military_grid_reference_system.

**Comment by breversa** [comment]
That feature would be useful for many people in the militaries around the world (or at least NATO ?).

**Comment by maugsburger** [comment]
I didn't think of militaries, but it is also used in the civil defence and rescue service in germany.

**Comment by cnelk** [comment]
+1
http://www.jstott.me.uk/jcoord/ is a GPL licensed library that implements it and others.

**Comment by mvglasow** [comment]
Thanks for the pointer. I've had another merge request for coordinates in degrees/minutes/seconds – I'm thinking about implementing a choice between all three representations.
