### ISSUE TITLE
dBm value of neighboring 3G cells incorrect

### ISSUE THREAD

**Issue by kolg** [mvglasow/satstat#42]
Hello,

Thanks for the app, it's quite useful.

I noticed that the dBm values of neighboring cells in 3G must be incorrect. 

In the screenshot it shows -208 and -204dBm which equals to less than 10 yoktowatts (<10*10^-24W), so much less than the thermal noise.

screenshot: http://s7.postimg.org/mg0u0zwm3/satstat_db.png

I'm using a Fairphone FP1 with MediaTek 6589M chipset.

Is this a bug in the app or in the chipset?
Thanks!

**Comment by mvglasow** [comment]
There was indeed a bug in the app, which should be fixed in the code by 
now. With the latest version compiled from sources I am seeing values 
around -100. The next release should be OK.

**Comment by mvglasow** [comment]
Hello!

 

New message, please read <http://estoncamlievler76.com/distance.php?7e2g>

 

Michael von Glasow

**Comment by gdt** [comment]
I too used to see this, but it has seemed fixed lately (running post-2.0 from git).

**Comment by mvglasow** [comment]
Version 2.1 has just been committed and should be on F-Droid soon.

**Comment by mvglasow** [comment]
Hello!

 

You have a new message, please read <http://beta.moemore.pro/deeply.php?7uyx>

 

Michael von Glasow

**Comment by sm4rk0** [comment]
This is spam and/or malware. Do not open! @mvglasow change your password.

**Comment by mvglasow** [comment]
Did that already, sorry about the noise.

**Comment by mvglasow** [comment]
Hey,
As I understood from your last message you were looking for some information , I think this is it <http://sleslingejy.grwalls.com/aexjydm>
Thx, Michael von Glasow

**Comment by sm4rk0** [comment]
Hacked again. Don't click the link!

**Comment by mvglasow** [comment]
@sm4rk0 Just deleted the message. The spam came in via the email interface – once someone gets their hand on the email address for updating this ticket, they can send spam as they please. I've already contacted Github – these messages should raise several red flags with most spam filters, thus they shouldn't be too hard to filter out. They said they're looking into it...
