### ISSUE TITLE
Sorted WiFis

### ISSUE THREAD

**Issue by fiaxh** [mvglasow/satstat#44]
It would be nice to have WiFis sorted by name / MAC / dBm or to even have the possibility to select what they are sorted by.
Right now its a quite cumbersome task to keep track of multiple WiFis using SatStat.

**Comment by mvglasow** [comment]
You're right, this one could use some improvement. Right not I'm not quite sure about the best sort order – SSID/MAC would be the most stable but somewhat arbitrary. Signal strength is more logical but less stable as signal strengths will always oscillate around a certain mean value.

What is already implemented: tapping a wifi will pin it to the top of the list – but this works only for one wifi in the list.

**Comment by mvglasow** [comment]
Just pushed a commit that introduces that feature. The sort criterion is configurable in the preferences (BSSID, SSID, channel, signal strength). BSSID is used as a secondary sort criterion if the first is not sufficient.

**Comment by gdt** [comment]
I've been sorting by signal strength; it seems to work reliably and I like it.   I think what you've done is good enough for this ticket (perhaps you only close when there's a release with the fix).

**Comment by mvglasow** [comment]
I've marked the issue as resolved and will close it when the release is out.
