### ISSUE TITLE
GSM information moved to the right

### ISSUE THREAD

**Issue by tomikmar** [mvglasow/satstat#46]
Sometimes GSM information is moved to the right (see screenshot).
![phone-screenshot-2015-05-16-15-52-16](https://cloud.githubusercontent.com/assets/5788375/7666456/644b6e28-fbe6-11e4-9365-a1696c215f27.png)

I use version 2.0 from F-Droid.

**Comment by rdoeffinger** [comment]
That actually was a bug in the LTE formatting, and was fixed by 51f2095f2bda1e6d8d128be5e7cd207fbb9bfd51
We're just missing a release with it, it seems.

**Comment by mvglasow** [comment]
Yes, this part is still having issues. I fixed some but SatStat still has trouble identifying the cell type when the network switches between 3G and LTE, which is why I haven't released a new version yet.

**Comment by mvglasow** [comment]
It looks like I might have fixed the issue (things look good so far – switching between LTE and UMTS no longer gives me the display errors I have seen in the past). I'm planning to prepare a new release in the next few weeks, which should fix various cell display issues.

**Comment by mvglasow** [comment]
Version 2.1 has just been committed and should be on F-Droid soon.
