### ISSUE TITLE
How to Install on Samsung Note 3

### ISSUE THREAD

**Issue by theGuruWithin** [mvglasow/satstat#49]
How to Install on Samsung Note 3.
is there an .apk available or some way to install repository zip download on phone?

thanks for awesome work

**Comment by mvglasow** [comment]
You can get SatStat on F-Droid:

https://f-droid.org/repository/browse/?fdfilter=satstat&fdid=com.vonglasow.michael.satstat

Either you install the F-Droid client (which will also notify you when updates are available), or you can just download the APK from the page.
