### ISSUE TITLE
Hang with black screen when in Airplane Mode

### ISSUE THREAD

**Issue by sappjw** [mvglasow/satstat#51]
When in Airplane Mode, after starting SatStat it hangs with a black screen.  There's no way out except to kill the application.  When I disable Airplane Mode (and SatStat is not running), the application seems to work fine.  I can get a logcat if you'd like.

**Comment by rdoeffinger** [comment]
Are you using an Android version that disables GPS when you enable airplane mode?
I can't reproduce the issue on any of my devices, but they all run Android 5.1...
(I am not the app developer, just an interested "bystander")

**Comment by sappjw** [comment]
I don't think so. My device is running 4.4.4, but even so I think it shouldn't just hang.

**Comment by mvglasow** [comment]
@sappjw yes, a logcat would definitely help. I've designed SatStat to work even without a GPS present and tested it successfully in emulators, but behavior may vary between devices. If you can get a logcat right after the crash, I can investigate what causes the crash on your device.

**Comment by sappjw** [comment]
This is no longer an issue in the latest version.
