### ISSUE TITLE
No location permission => app exception

### ISSUE THREAD

**Issue by andree182** [mvglasow/satstat#67]
After installing the app, it may not have the location permissions enabled (in my case, Android 6.0.1 + ADB). Then the following happens:

`java.lang.RuntimeException: Unable to resume activity {com.vonglasow.michael.satstat/com.vonglasow.michael.satstat.MainActivity}: java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.`

Correct behavior would be to not show location - but the app should not terminate with exception... E.g. GPSTest works this way.

**Comment by licaon-kter** [comment]
Looks like it needs to implement the ask permission thing for Android >6.0.

**Comment by mvglasow** [comment]
You're right, didn't have that on my radar yet. For now you'll have to make sure SatStat is granted the permissions it asks for. I'll fix that in the next release.

**Comment by mvglasow** [comment]
I've just committed a bugfix release, which should become available on F-Droid in a few days.

**Comment by mvglasow** [comment]
The new release is available on F-Droid. Can you test and report if this fixes it?

**Comment by andree182** [comment]
Well, it doesn't fail on exception now, but it doesn't seem to request the location permissions (so nothing in the GPS/BTS views)... Could be just my setup though...

**Comment by mvglasow** [comment]
Yes, that's the way it's currently implemented. SatStat expects permissions to be granted beforehand, else functions which depend on the missing permissions will not be available.

**Comment by breversa** [comment]
Why doesn't Satstat request permissions like all location apps ? What's the rationale behind that behaviour ?

**Comment by licaon-kter** [comment]
I guess it was not (yet) updated to be compatible with Android 6 permission scheme.

**Comment by kadarivan** [comment]
SatStat needs and has permissions, just like any other apps. (Xperia Z3C 6.0.1)
![screenshot_20160623-225321](https://cloud.githubusercontent.com/assets/18245793/16320030/13132f20-3996-11e6-9a0d-a976580799ce.png)
![screenshot_20160623-225334](https://cloud.githubusercontent.com/assets/18245793/16320034/138f28dc-3996-11e6-9f72-da3d0d866109.png)
![screenshot_20160623-225341](https://cloud.githubusercontent.com/assets/18245793/16320031/13432c84-3996-11e6-93e3-c5fa8e421ee0.png)

**Comment by licaon-kter** [comment]
Yes, but did it ASK for for it on first start?

**Comment by breversa** [comment]
I confirm : it does not ask for permissions (fresh install on a new phone).

One needs to know where to look and manually enable them.

2016-06-24 0:20 GMT+02:00 licaon-kter <notifications@github.com>:

**Comment by mvglasow** [comment]
Asking for permissions is currently not implemented – what is currently there is a stop-gap solution just to prevent it from crashing if permissions are not there. I haven't yet tried a fresh install on Android 6.0.1 – will look into it for the next version and implement the proper mechanism.

**Comment by mvglasow** [comment]
I've made some progress in that direction. SatStat will now request all permissions which are needed by any UI component (location and storage, the latter only if offline maps are used) if they are not granted. If the user grants the permission, the corresponding features are enabled; if the user denies the permission, SatStat shows a toast alert that some features will not be available.

The only thing left to do is to ask for permissions for operations which happen in the background (e.g. listening for locations to display the notification, refreshing AGPS data in the background). The confirmation dialog is bound to an Activity, hence I can't have the service pop up a dialog.

**Comment by Minoru** [comment]
Just built from the repo and can confirm that indeed, things work fine on Sony Xperia D5803. Thanks!

**Comment by mvglasow** [comment]
More progress has been made over the past days: non-UI components will now display a notification to request permissions. Additionally, permissions are requested in Settings upon selecting an option that requires them (such as GPS status notification or AGPS data download). Still need to work on a few minor things – apart from that, things should by now be complete.

**Comment by mvglasow** [comment]
Runtime permission support is now feature complete. One minor glitch: if you press Home while a runtime permission dialog is active (e.g. if it was brought up via notification) and then return to SatStat, you need to respond to that dialog first, then retry. Unfortunately there seems to be no way for SatStat to close it.

**Comment by mvglasow** [comment]
Version 3.0 was released on F-Droid today. This version fully implements runtime permissions. Closing this one – if there are still issues, feel free to reopen.
