### ISSUE TITLE
Show satellite country

### ISSUE THREAD

**Issue by MaDill** [mvglasow/satstat#68]
It would be nice if there would be the possibility to see the country of the satellite. Maybe by form or color. Then you can see if the device can detect only the US satellites or/and also the Russian, Chinese...

**Comment by mvglasow** [comment]
I'm planning to add labels for this to the SNR chart (the bar chart at the bottom) in the next release, see #64. You can already see this in the current version – the SNR chart has multiple ranges, separated by a slightly more prominent line. The first is GPS, the second is GLONASS and the third is Beidou. Color is currently used to indicate whether a satellite is used in the fix.

Visualizing this in the sky plot is going to be more challenging – this is being discussed in #69.
