### ISSUE TITLE
Satstat crash in map

### ISSUE THREAD

**Issue by licaon-kter** [mvglasow/satstat#73]
Android 6.0.1, 2.2 from F-Droid

Worked fine otherwise (#67 granted), crashed in the mapview IIRC: https://gist.github.com/licaon-kter/168c97b3a2aae488984f35acd25f94e8

**Comment by mvglasow** [comment]
The crash appears to happen directly in Mapsforge, no SatStat code in the call stack. Does this happen frequently?

I'm currently working on the next version of SatStat, which will include a new Mapsforge version (the upcoming 0.6.1) Both the new Mapsforge version and the new SatStat version will fix some bugs which could previously cause crashes.

**Comment by licaon-kter** [comment]
Only once so far.

**Comment by mvglasow** [comment]
Version 3.0 was released on F-Droid today, which fixes several crash issues (including #67). Feel free to reopen if you still experience crashes.
