### ISSUE TITLE
add way to see both unsplit cellid and RNCID/CID, or quick mechanism to change

### ISSUE THREAD

**Issue by gdt** [mvglasow/satstat#77]
I like being able to split, but it seems the world is such that both representations are and wlll be in use.    So I'd like to be able to absorb both easily.

Ideas:
 * On phones there isn't enough room, so if all cells reported have the same mcc/mnc, put mcc/mnc after the "GSM" and omit those columns.  Then add both representations.
 * Add a line with the other form for the current cell (only).
 * have a short tap on the cell table (or in that CID column) change the preference.

Probably the third approach is easiest and is probably enough to solve the problem with minimal display impact to others.

**Comment by mvglasow** [comment]
Valid point, I'm just not yet sure what the best UX for that would be. 

* MCC/MNC are not guaranteed to be the same for all – think dual-sim phones with SIMs from two different carriers. Or the API might just report bogus data (which we want to catch, too). Bottom line: dropping MCC/MNC may result in loss of information.
* Adding another line might work, but at the expense of screen real estate. And if we do it for the current cell, someone soon might ask for all cells to show both ID representations.
* Tapping on the cell – although I have in the past merged a contribution for the WiFi list which allows users to pin a WiFi to the top of the list by tapping it, I realize many users don't know about this. Looking back, that was suboptimal from a UX point of view.

Other options would be:
* A button to switch between both representations quickly (which begs the next question: where are we going to put it?)
* Two-line display (as above) for all cells, but with an option to enable or disable it. It would require extra screen real estate if enabled, but users have the choice to turn the feature on or off.

**Comment by mvglasow** [comment]
I've added an option to show or hide both ID forms. The selected format is always on top, the other one displays underneath it, in a smaller font, if enabled. The setting takes effect for all cells.

**Comment by gdt** [comment]
Sorry for not responding to your earlier comments - I missed them.   I saw the new UI and I really like it.  In my case, the other cells have mcc/mnd, psc and dBm, but no LAC and no cellid.   Thanks for adding this.

**Comment by mvglasow** [comment]
This normal behavior on UMTS and LTE networks – for neighboring cells only the PSC is available, as the modem won't see the LAC/TAC and cell ID until it actually registers with the cell. GSM-based networks are different – there is no PSC (since the networks are TDMA-based and PSC is a CDMA concept) and the model gets the full ID of all neighboring cells.
