### ISSUE TITLE
Hide satellites with invalid azimuth/elevation

### ISSUE THREAD

**Issue by mvglasow** [mvglasow/satstat#8]
Under certain circumstances satellites appear at the tip of the compass arrow in the sky plot, i.e. azimuth and elevation of 0°. These are most likely satellites for which ephemeris is not available, so check for hasEphemeris() and  display only satellites for which true is returned.

**Comment by tomikmar** [comment]
I have the same problem on p5100 with Cyanogenmod 11-20150517-nightly (Android 4.4.4). It periodically switches between correct and incorrect view. 

    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 13, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 15, snr=35,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 16, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 18, snr=36,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 19, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 21, snr=26,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 22, snr=40,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 26, snr=21,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 27, snr=13,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.394 D/GpsStatusView(3297): Satellite 30, snr=18,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.401 D/GpsStatusView(3297): Satellite 69, snr=15,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=false
    05-26 21:57:03.401 D/GpsStatusView(3297): Satellite 70, snr=36,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=false
    05-26 21:57:03.401 D/GpsStatusView(3297): Satellite 71, snr=41,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.401 D/GpsStatusView(3297): Satellite 85, snr=33,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 4, snr=19,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 7, snr=16,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 13, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 15, snr=35,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 16, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 18, snr=36,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 19, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 21, snr=26,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.784 D/GpsStatusView(3297): Satellite 22, snr=40,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 26, snr=21,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 27, snr=13,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 30, snr=18,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 69, snr=15,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=false
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 70, snr=36,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=false
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 71, snr=41,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.792 D/GpsStatusView(3297): Satellite 85, snr=33,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.878 D/GpsStatusView(3297): Satellite 4, snr=19,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.878 D/GpsStatusView(3297): Satellite 7, snr=16,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 13, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 15, snr=35,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 16, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 18, snr=36,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 19, snr=14,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 21, snr=26,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true
    05-26 21:57:03.886 D/GpsStatusView(3297): Satellite 22, snr=40,000000, azimuth=0,000000, elevation=1,000000, almanac=false, ephemeris=false, used=true

**Comment by mvglasow** [comment]
Just examined a log of the same issue on the OnePlusOne (bacon), CM13. Things look a bit different here:

```
04-05 21:39:42.575: D/GpsStatusView(6722): Satellite 9, snr=0.000000, azimuth=0.000000, elevation=0.000000, almanac=true, ephemeris=true, used=false
04-05 21:39:42.575: D/GpsStatusView(6722): Satellite 82, snr=0.000000, azimuth=0.000000, elevation=0.000000, almanac=false, ephemeris=false, used=false
04-05 21:39:42.575: D/GpsStatusView(6722): Satellite 207, snr=26.200001, azimuth=0.000000, elevation=0.000000, almanac=false, ephemeris=false, used=false
04-05 21:39:42.575: D/GpsStatusView(6722): Satellite 208, snr=25.200001, azimuth=0.000000, elevation=0.000000, almanac=true, ephemeris=true, used=true
04-05 21:39:42.576: D/GpsStatusView(6722): Satellite 217, snr=24.200001, azimuth=0.000000, elevation=0.000000, almanac=false, ephemeris=false, used=false
04-05 21:39:42.576: D/GpsStatusView(6722): Satellite 227, snr=23.600000, azimuth=0.000000, elevation=0.000000, almanac=false, ephemeris=false, used=false
```

and in another instance

```
04-05 21:43:43.690: D/GpsStatusView(6722): Satellite 9, snr=0.000000, azimuth=0.000000, elevation=0.000000, almanac=true, ephemeris=true, used=false
04-05 21:43:43.690: D/GpsStatusView(6722): Satellite 207, snr=25.600000, azimuth=0.000000, elevation=0.000000, almanac=false, ephemeris=false, used=false
04-05 21:43:43.691: D/GpsStatusView(6722): Satellite 208, snr=24.700001, azimuth=0.000000, elevation=0.000000, almanac=true, ephemeris=true, used=true
```

Here the satellites with bogus data always report zero elevation, and some report having an almanac and ephemeris. The satellites in question are a nice mix of GPS, GLONASS and Beidou. In the second log excerpt, PRN 208 is even reported as "used in fix", although this is cannot be correct as I didn't have a fix at the time (I see this happening more often, with satellites reported to be used in the fix when I don't have a fix).

Main takeaway here: GPS diagnostic data on most Android devices is a huge mess. Information provided by the API on almanac, ephemeris, sats used to get a fix and the position of a satellite is notoriously unreliable. There seems to be little incentive for vendors to do QA on these portions of the API, possibly for lack of apps that depend on the accuracy of such data.

I am somewhat undecided as to what to do: given that SatStat is a diagnostic app, maybe it is best to reveal all these things in their full ugliness so we can actually see what's happening under the hood (and who knows, maybe some vendors will eventually start using SatStat for QA :-). #48 points in a similar direction.

**Comment by mvglasow** [comment]
Logging was removed in 8097973.

Thanks @tomikmar for the input, it seems most (if not all) Android phones report bogus data under the hood. The purpose of SatStat is to find out such things, and any filtering would go against that purpose – therefore I'll leave things as they are.
