### ISSUE TITLE
UTM coordinates

### ISSUE THREAD

**Issue by elmat0** [mvglasow/satstat#80]
Is it possible to display coordinates in UTM format?

**Comment by breversa** [comment]
Go to Configuration (or whatever it's called in you language)/Coordinates, and choose "MGRS" (https://en.wikipedia.org/wiki/Military_grid_reference_system).

**Comment by elmat0** [comment]
Hmm. I don't have any options like that in the settings menu. I am using the binary provided by F- Droid. I'm guessing this feature is a recent addition.

**Comment by breversa** [comment]
Weird : it's been there for a long time already. Second parameter in the
configuration menu, between "Use metric units" and "Display GPS time in
UTC".

**Comment by elmat0** [comment]
Aah. I reinstalled fdroid and it now shows satstatv2.2 :) Now I have the extra settings.

Thanks

**Comment by breversa** [comment]
Glad I could help. :-) Don't forget to close the issue then !
