### ISSUE TITLE
Map view not functional any longer

### ISSUE THREAD

**Issue by guek** [mvglasow/satstat#86]
Instead of the map there comes a message from MapQuest, that the direct tile access has been discontinued since July 11, 2016.
See http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by gdt** [comment]
You can download offline maps to use with the included mapsforge library, at least in the development version.   This is preferable because it doesn't need a network connection, doesn't use data, and doesn't leak your location.  Of course, it requires downloading.

I would suggest that online tiles be configured off in the build, so that satstat uses offline maps only.

**Comment by guek** [comment]
@ gdt I have version 2.1 which is the latest from f-droit. I did not find something to configure an offline-map. Does Android know something like a "Offline Map Provider" to be used by different applications? I feel it to be weird that every app must use its own map storage.

**Comment by gdt** [comment]
I started building it myself a while ago.   f-droid's web page says 2.2, and so does the app.   But there are 178 commits since then (including merges and translation updates).

See #65 for the ticket about offline maps.

See https://github.com/mapsforge/mapsforge/issues/832 for discussion of the shared map issue.

I have created a directory on the sd card (virtual internal sd card) mapsforge, and put maps in that, and pointed satstat at it, and I think maybe also radiocells.   Setting that up as normal was the point of the mapsforge ticket.

**Comment by guek** [comment]
@gdt Thanks a lot! I had to reinstall my f-droit for being able to update apps again. :-)
I've read the discussions you pointed me to and it sounds promising!
Should i close this issue or wait until it is fixed in a release?

**Comment by gdt** [comment]
I think it should remain, because even git master has the problem if you choose online maps.

**Comment by mvglasow** [comment]
+1, the ticket should remain open. I didn't have the shutdown of the Mapsforge tile service on my radar – the offline maps were intended as an alternative to online tiles and I'd still like to keep both options. Offline maps are great if you've done your homework and downloaded maps for your area, and your device can handle rendering in a reasonable time (which is mostly a question of zoom level). Online tiles are more of a "quick start"

**Comment by n76** [comment]
You might want to check out what the microG project is doing with respect to maps API v1 or V2. If I understand things, the old v1 API is basically a wrapper for code from [OsmDroid](https://github.com/osmdroid/osmdroid). And, I think, V2 (implemented in [gmsCore](https://github.com/microg/android_packages_apps_GmsCore)) uses OpenScienceMap.

**Comment by mvglasow** [comment]
@n76 Thanks for the link. SatStat currently uses [Mapsforge](http://www.mapsforge.org), which offers most (if not all) of the functionality found in OsmDroid and even more (as OsmDroid, to my knowledge, does not support rendering of vector maps). OpenScienceMap does look like an interesting alternative to pre-rendered tiles, especially as the map data appears to be downloaded live and there seems to be no usage limit. I'd also expect superior quality on high-resolution devices (anything north of the 120dpi bin, which means pretty much all Android devices). On the other hand, it's probably not going to be a drop-in replacement but requires some work. Thus it's probably not going to happen in the next version (which I intend to release as soon as I have found an alternative source of raster tiles – with the old source lost, I need to act fast) but it could be looked at for a later version.

**Comment by mvglasow** [comment]
Good news: I got permission from OSM to use their tile servers. They don't consider the typical usage pattern of SatStat to be an issue (it should be similar to a browser with some panning and zooming, or to OSM Tracker for Android).

As this is much quicker than fiddling around with API keys and hard usage limits, or swapping out the map library, I'll move to OSM tiles for now. Other tile sources, or vector tiles, can be considered for later versions.

**Comment by n76** [comment]
Will you be tagging a new version? Looks like lots of changes/improvements since the 2.2 tag on 9May. . .

Without a new version tag, I am not sure F-Droid will build a new version.

**Comment by mvglasow** [comment]
There will be a new version. I just need to check what parts of the code need cleaning up – once that's done, I'll tag the new version so F-Droid can pick it up.

**Comment by mvglasow** [comment]
I tagged the satstat-3.0 release today (it's a major version, since it comes with various new features); it should appear on F-Droid in the next couple of days.

**Comment by gdt** [comment]
The satstat-3.0 tag plus the 3.1  version commit works for me, both on-line and off-line maps.  Thanks for all the effort to improve this - I think it's much nicer now.

**Comment by n76** [comment]
Thanks!

**Comment by mvglasow** [comment]
Version 3.0 is on F-Droid, closing this one

**Comment by guek** [comment]
Thank you!
