### ISSUE TITLE
Speed in notification bar is printed in knots by default

### ISSUE THREAD

**Issue by mst23** [mvglasow/satstat#92]
In the notification bar, the speed is printed in knots by default.
To use km/h, you have to check AND THEN uncheck the checkbox for knots in the settings menu.

**Comment by mvglasow** [comment]
Indeed, this is a bug in 3.0. Fixed in 3.1, which was tagged yesterday and should be on F-Droid soon.

**Comment by mvglasow** [comment]
3.1 was released on F-Droid today.
